# ~~~~ File Type : Docker file ~~~~~~~~~~~ #
# ~~~~~~ Package : gcc  ~~~~~~~~~~~~~~~~~~ #
# ~~~~~~~ Author : Vaibhav Vaingankar ~~~~ #

FROM ubuntu:15.10
MAINTAINER Vaibhav Vaingankar (vaibhav_vaingankar@persistent.com)
RUN apt-get update && apt-get install -y gcc
